In [105]:
import numpy as np
from scipy.stats import ortho_group as og

In [ ]:
A = np.array([[1,2],[3,4]])
eval, evec = np.linalg.eig(A)
print (eval)
print(evec)fsdfs

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [84]:
A = evec
D = np.diag(eval)
print(A@D)
print(D@A)


[[ 0.30697009 -2.23472698]
 [-0.21062466 -4.88542751]]
[[ 0.30697009  0.15485919]
 [ 3.03946199 -4.88542751]]


In [ ]:
# Eigenvector of a symmetric matrix are pair-wise orthogonal
# Symmetric matrix is a square matrix that is equal to its transpose
A = np.random.randint(-3,3,(3,3))
A = A.T@A #Symmetric matrix is created here
V,C = np.linalg.eig(A)
print(np.dot(C[:,0],C[:,1]))
print(np.dot(C[:,0],C[:,2]))
print(np.dot(C[:,1],C[:,2]))

0.0
-6.938893903907228e-17
-4.996003610813204e-16


In [ ]:
#An eigenvector, scaled by its norm, when np.dot'ed with itself 
#will output an identity matrix (just like any symmetric matrix)
#
N = np.linalg.norm(C, axis=0)
print(N)
CU = C/N
print(C)
print(CU)
print(np.round(CU@CU.T,2))
print (np.round(C@C.T))


[1. 1. 1.]
[[-0.94173225  0.33487695  0.03158797]
 [ 0.12256075  0.25416823  0.95936301]
 [-0.3132399  -0.90733453  0.28040119]]
[[-0.94173225  0.33487695  0.03158797]
 [ 0.12256075  0.25416823  0.95936301]
 [-0.3132399  -0.90733453  0.28040119]]
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [115]:
#A symmetric matrix scaled to its unit length when np.dot'ed 
#with itself will not produce an identity matrix since it is not
#orthogonal 
A = np.random.randint(-5,5,(4,4))
A = A.T@A
N = A/np.linalg.norm(A, axis=0)
print(N.T@N)

#orthogonal matrix
oN = og.rvs((3))
print(oN)
#Randome orthogonal matrix np.dot'ed with itself creates 
#an identity matrix 
print(np.round(oN.T@oN,2))

[[1.         0.4994843  0.87513852 0.17811074]
 [0.4994843  1.         0.80924947 0.91395609]
 [0.87513852 0.80924947 1.         0.5117199 ]
 [0.17811074 0.91395609 0.5117199  1.        ]]
[[ 0.38936372  0.90544463  0.16901452]
 [ 0.71278891 -0.4124146   0.56731487]
 [-0.58337626  0.10042015  0.80597018]]
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [141]:
A = np.random.randint(0,9,(3,3))
L,V = np.linalg.eig(A)
print(A)
print(L)
# print(V)
print((A-np.diag(L))@V,2)


[[3 0 7]
 [1 2 1]
 [1 1 4]]
[6.59140572+0.j         1.20429714+0.82075958j 1.20429714-0.82075958j]
[[ 3.55271368e-15+0.00000000e+00j -4.37953445e+00+6.67249378e-01j
  -4.37953445e+00-6.67249378e-01j]
 [ 1.51570999e+00-2.30927868e-01j -6.10622664e-16-2.77555756e-16j
   7.18425543e-01+5.05850269e-01j]
 [ 2.35978616e+00+3.59528135e-01j -1.56471805e-01-3.42337605e-01j
   3.19189120e-16-6.93889390e-16j]] 2
